/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Z500-PC' at '12/7/17 6:17 PM' with Gradle 2.14.1
 *
 * @author Z500-PC, @date 12/7/17 6:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
